spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=X-Gateway, SpringGateway

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=X-Gateway, SpringGateway
